services:
  user-service:
    build: ./user-service
    container_name: user-container
    ports:
      - "3001:3000"
    env_file:
      - .env

    depends_on:
      - mongodb

  product-service:
    build: ./product-service
    container_name: product-container
    ports:
      - "3002:3000"
    env_file:
      - .env

    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/mydb

volumes:
  mongo-data: